// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Configuration;
using System.Diagnostics;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace ESS_Web_Services.My
{
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : ApplicationSettingsBase
    {
        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        /* TODO ERROR: Skipped RegionDirectiveTrivia *//* TODO ERROR: Skipped IfDirectiveTrivia *//* TODO ERROR: Skipped DisabledTextTrivia *//* TODO ERROR: Skipped EndIfDirectiveTrivia *//* TODO ERROR: Skipped EndRegionDirectiveTrivia */
        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia *//* TODO ERROR: Skipped DisabledTextTrivia *//* TODO ERROR: Skipped EndIfDirectiveTrivia */
                return defaultInstance;
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("INT001-1143-016")]
        public string GrapeVineAffiliate
        {
            get
            {
                return Conversions.ToString(this["GrapeVineAffiliate"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("EMAPPLINK")]
        public string GrapeVineAuthentication
        {
            get
            {
                return Conversions.ToString(this["GrapeVineAuthentication"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("https://bms8.vine.co.za/webservice/services/ApplinkUpload")]
        public string GrapeVineUrl
        {
            get
            {
                return Conversions.ToString(this["GrapeVineUrl"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("729ff8a5-4e36-42e9-9ba5-2a71021a1b8e")]
        public string SysmanSmsID
        {
            get
            {
                return Conversions.ToString(this["SysmanSmsID"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("MeYpxARMlldAceIfUqEAiSO4B+oVb/Gq")]
        public string SysmanSmsKey
        {
            get
            {
                return Conversions.ToString(this["SysmanSmsKey"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("sherwyn@izaiahinvestments.co.za")]
        public string ZoomConnectUserName
        {
            get
            {
                return Conversions.ToString(this["ZoomConnectUserName"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("f6b91fce-749a-4f1c-9a29-70d58bb7b707")]
        public string ZoomConnectToken
        {
            get
            {
                return Conversions.ToString(this["ZoomConnectToken"]);
            }
        }

        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [SpecialSetting(SpecialSetting.WebServiceUrl)]
        [DefaultSettingValue("http://localhost/esswebservices/pagingservice.asmx")]
        public string ESS_Web_Services_ServiceReferencePaging_PagingService
        {
            get
            {
                return Conversions.ToString(this["ESS_Web_Services_ServiceReferencePaging_PagingService"]);
            }
        }
    }
}

namespace ESS_Web_Services.My
{
    [HideModuleName()]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal static class MySettingsProperty
    {
        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}